name: Ubuntu

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: CXX=g++-9 cmake -Htest -Bbuild -DENABLE_TEST_COVERAGE=1

    - name: build
      run: cmake --build build --config Debug -j4

    - name: test
      run: |
        cd build
        ctest --build-config Debug

    - name: install code coverage tools
      run: |
        sudo apt-get install llvm-9
        wget https://github.com/linux-test-project/lcov/releases/download/v1.14/lcov-1.14.tar.gz
        tar xvfz lcov-1.14.tar.gz;
        sudo make install -C lcov-1.14

    - name: collect code coverage
      run: |
        printf '#!/bin/bash\nexec llvm-cov-9 gcov "$@"' > llvm-gcov.sh
        chmod +x llvm-gcov.sh
        lcov --gcov-tool "$(pwd)/llvm-gcov.sh" --directory . --exclude "*_deps*" --capture --no-external --quiet --output-file  coverage.info
        lcov --gcov-tool "$(pwd)/llvm-gcov.sh" --list coverage.info
        bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
